In [2]:
# Numpy --> Fundamental library for scientific computation in python.
# Provides support for array and matrices along with collection of mathematical 
# functions to operate on these data structures. 
# We focus on arrays and vectorized operations.

import numpy as np 
# create array using numpy 
# create an array 
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print("Shape of array is ",arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
Shape of array is  (5,)


In [ ]:
arr2 = np.array([1,2,3,4,5])
#1,5 means 1 row and 5 columns
arr2.reshape(1,5) 
print(arr2)

[1 2 3 4 5]


In [11]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [13]:
arr2 = np.array([[1,2,3,4,5],[5,6,7,8,9]])
arr2.shape

(2, 5)

In [ ]:
# Elements in range from 0 to 10 with step size of 2
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [5]:
# Create 1-D array having 3 rows and 4 columns having all values as 1
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
# Creating an identity matrix
# All diagnol elements will be one and remaining will be zero
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
arr = np.array([[1,2,3],[4,5,6]])
print("Array \n",arr)
print("Shape: ",arr.shape)
print("Number of dimensions ",arr.ndim)
print("Size(no of elements) ",arr.size)
print("Item size(in bytes) ",arr.itemsize)

Array 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions  2
Size(no of elements)  6
Item size(in bytes)  8


In [14]:
## Numpy vectorized operation 
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element wise addition 
print("Addition: ",arr1+arr2)

# Element wise substraction 
print("Substraction: ",arr1-arr2)

# Element wise multiplication 
print("Multiplication: ",arr1*arr2)

# Element wise division 
print("Division: ",arr1/arr2)

Addition:  [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [19]:
## Universal functions 
## Some functions that applies to entire array
arr = np.array([1,2,3,4,5,6])
## Square root 
np.sqrt(arr)
## Exponential 
np.exp(arr)
## Sine 
np.sin(arr)
## Log 
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947])

In [23]:
## array slicing and indexing 
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
array[0][0]

np.int64(1)

In [31]:
array[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [34]:
print(array[0:2,2:])

[[3 4]
 [7 8]]


In [36]:
print(array[1:,1:3])

[[ 6  7]
 [10 11]]


In [38]:
array[0][0] = 100
print(array)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [39]:
# Statistical operations 
data = np.array([1,2,3,4,5])

mean = np.mean(data)
std_dev = np.std(data)

normalized_data = ((data - mean)/std_dev)

variance = np.var(data)
print("Variance: ",variance)

Variance:  2.0


In [44]:
## Logical operation 
data = np.array([1,2,3,4,5,6,7,8,9,10])
data>5
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])